import 'package:flutter/material.dart';
import '../../../design_system/foundations/app_colors.dart';
import '../../../shared/models/localized_text.dart';
import 'fortune_definition.dart';

/// Source of truth for every fortune family (Sprint 01).
/// Adding a fortune here is the ONLY change needed for it to appear in
/// Explore and gain a working Ritual Entry.
abstract final class FortuneRegistry {
  static const RitualPace _pace = RitualPace(
    enter: Duration(milliseconds: 500),
    step: Duration(milliseconds: 150),
  );

  // Per-fortune jewel accents: the four category accents + a few extras, so
  // each fortune's moon glow and ritual aura reads distinctly.
  static const _gold = CategoryAccents.hafez;
  static const _turq = CategoryAccents.tarot;
  static const _blue = CategoryAccents.dream;
  static const _rose = CategoryAccents.love;
  static const _copper = CategoryAccents.coffee;
  static const _violet = Color(0xFFA78BFA);
  static const _emerald = Color(0xFF5FBF8F);
  static const _amber = Color(0xFFE6A23C);
  static const _teal = Color(0xFF4FB6B0);
  static const _magenta = Color(0xFFCB6FB0);
  static const _sky = Color(0xFF6FA8DC);
  static const _jade = Color(0xFF7FC8A9);

  /// Every fortune family: the four backend-live rituals + coffee (soon), then
  /// the remaining catalog fortunes activated with shared ritual copy — each
  /// gets its own faithful voice from the backend framing, not this screen.
  static final List<FortuneDefinition> all = [..._core, ..._extended];

  static const List<FortuneDefinition> _core = [
    FortuneDefinition(
      id: 'hafez',
      accent: CategoryAccents.hafez,
      inputKind: FortuneInputKind.intention,
      title: LocalizedText(
        fa: 'فال حافظ',
        en: 'Hafez',
        ar: 'فأل حافظ',
        tr: 'Hafız Falı',
      ),
      subtitle: LocalizedText(
        fa: 'نیت کن و از دیوان بپرس',
        en: 'Hold an intention, ask the Divan',
        ar: 'انوِ نيّتك واسأل الديوان',
        tr: 'Niyet et, Divan\'a sor',
      ),
      ritualLine: LocalizedText(
        fa: 'نیتت را در دل نگه دار.',
        en: 'Hold your intention in your heart.',
        ar: 'احتفظ بنيّتك في قلبك.',
        tr: 'Niyetini kalbinde tut.',
      ),
      placeholder: LocalizedText(
        fa: '…یا این‌جا با خودت بگو',
        en: '…or whisper it here',
        ar: '…أو اهمس بها هنا',
        tr: '…ya da burada fısılda',
      ),
      cta: LocalizedText(
        fa: 'فال حافظ را باز کن',
        en: 'Open the Hafez reading',
        ar: 'افتح فأل حافظ',
        tr: 'Hafız falını aç',
      ),
      pace: RitualPace(
        enter: Duration(milliseconds: 500),
        step: Duration(milliseconds: 140),
      ),
    ),
    FortuneDefinition(
      id: 'tarot',
      accent: CategoryAccents.tarot,
      inputKind: FortuneInputKind.intention,
      title: LocalizedText(
        fa: 'تاروت',
        en: 'Tarot',
        ar: 'التاروت',
        tr: 'Tarot',
      ),
      subtitle: LocalizedText(
        fa: 'پرسشی که می‌خواهی روشن شود',
        en: 'A question seeking light',
        ar: 'سؤال تريد أن يستنير',
        tr: 'Aydınlanmasını istediğin bir soru',
      ),
      ritualLine: LocalizedText(
        fa: 'به پرسشی فکر کن که می‌خواهی روشن شود.',
        en: 'Think of the question you want illuminated.',
        ar: 'فكّر في السؤال الذي تريد أن يستنير.',
        tr: 'Aydınlanmasını istediğin soruyu düşün.',
      ),
      placeholder: LocalizedText(
        fa: '…یا این‌جا بپرس',
        en: '…or ask it here',
        ar: '…أو اسأل هنا',
        tr: '…ya da burada sor',
      ),
      cta: LocalizedText(
        fa: 'کارت‌ها را بکش',
        en: 'Draw the cards',
        ar: 'اسحب البطاقات',
        tr: 'Kartları çek',
      ),
      pace: RitualPace(
        enter: Duration(milliseconds: 600),
        step: Duration(milliseconds: 170),
      ),
    ),
    FortuneDefinition(
      id: 'dream',
      accent: CategoryAccents.dream,
      inputKind: FortuneInputKind.longText,
      title: LocalizedText(
        fa: 'تعبیر خواب',
        en: 'Dream',
        ar: 'تفسير الأحلام',
        tr: 'Rüya Tabiri',
      ),
      subtitle: LocalizedText(
        fa: 'خوابت را آرام تعریف کن',
        en: 'Tell your dream, gently',
        ar: 'احكِ حلمك بهدوء',
        tr: 'Rüyanı sakince anlat',
      ),
      ritualLine: LocalizedText(
        fa: 'خوابت را همان‌طور که به یادت مانده، آرام تعریف کن.',
        en: 'Tell your dream just as you remember it, gently.',
        ar: 'احكِ حلمك كما بقي في ذاكرتك، بهدوء.',
        tr: 'Rüyanı aklında kaldığı gibi, sakince anlat.',
      ),
      placeholder: LocalizedText(
        fa: 'از هر جایی که یادت می‌آید شروع کن…',
        en: 'Start anywhere you remember…',
        ar: 'ابدأ من أي موضع تتذكّره…',
        tr: 'Hatırladığın herhangi bir yerden başla…',
      ),
      cta: LocalizedText(
        fa: 'تعبیر خوابم را ببین',
        en: 'See my dream reading',
        ar: 'اعرض تفسير حلمي',
        tr: 'Rüya tabirimi gör',
      ),
      guide: LocalizedText(
        fa: 'برای شروع، چند کلمه از خوابت کافی است.',
        en: 'A few words of your dream are enough to begin.',
        ar: 'للبدء، تكفي كلمات قليلة من حلمك.',
        tr: 'Başlamak için rüyandan birkaç kelime yeter.',
      ),
      privacy: LocalizedText(
        fa: 'خوابت نزدِ خودت می‌مانَد؛ فقط برای همین تعبیر به کار می‌رود.',
        en: 'Your dream stays yours; it is used only for this reading.',
        ar: 'يبقى حلمك عندك؛ ولا يُستخدم إلا لهذا التفسير.',
        tr: 'Rüyan sende kalır; yalnızca bu tabir için kullanılır.',
      ),
      minWords: 3,
      maxLength: 2000,
      pace: RitualPace(
        enter: Duration(milliseconds: 660),
        step: Duration(milliseconds: 180),
      ),
    ),
    FortuneDefinition(
      id: 'love',
      accent: CategoryAccents.love,
      inputKind: FortuneInputKind.twoNames,
      title: LocalizedText(
        fa: 'فال عشق',
        en: 'Love',
        ar: 'فأل الحب',
        tr: 'Aşk Falı',
      ),
      subtitle: LocalizedText(
        fa: 'دو نام، یک پیوند',
        en: 'Two names, one bond',
        ar: 'اسمان، رابطة واحدة',
        tr: 'İki isim, tek bağ',
      ),
      ritualLine: LocalizedText(
        fa: 'دو نام، یک پیوند.',
        en: 'Two names, one bond.',
        ar: 'اسمان، رابطة واحدة.',
        tr: 'İki isim, tek bağ.',
      ),
      placeholder: LocalizedText(
        fa: 'نامِ تو',
        en: 'Your name',
        ar: 'اسمك',
        tr: 'Senin adın',
      ),
      placeholderSecond: LocalizedText(
        fa: 'نامِ او',
        en: 'Their name',
        ar: 'اسمه أو اسمها',
        tr: 'Onun adı',
      ),
      cta: LocalizedText(
        fa: 'سازگاری را ببین',
        en: 'See the harmony',
        ar: 'اعرض التوافق',
        tr: 'Uyumu gör',
      ),
      guide: LocalizedText(
        fa: 'برای دیدنِ سازگاری، هر دو نام را بنویس.',
        en: 'Write both names to see the harmony.',
        ar: 'لرؤية التوافق، اكتب الاسمين معًا.',
        tr: 'Uyumu görmek için iki ismi de yaz.',
      ),
      privacy: LocalizedText(
        fa: 'نام‌ها فقط برای همین فال استفاده می‌شوند.',
        en: 'The names are used only for this reading.',
        ar: 'لا تُستخدم الأسماء إلا لهذا الفأل.',
        tr: 'İsimler yalnızca bu fal için kullanılır.',
      ),
      maxLength: 60,
      pace: RitualPace(
        enter: Duration(milliseconds: 460),
        step: Duration(milliseconds: 130),
      ),
    ),
    FortuneDefinition(
      id: 'coffee',
      accent: CategoryAccents.coffee,
      inputKind: FortuneInputKind.photo,
      title: LocalizedText(
        fa: 'فال قهوه',
        en: 'Coffee',
        ar: 'قراءة الفنجان',
        tr: 'Kahve Falı',
      ),
      subtitle: LocalizedText(
        fa: 'رازهای تهِ فنجان',
        en: 'Secrets at the bottom of the cup',
        ar: 'أسرار قاع الفنجان',
        tr: 'Fincanın dibindeki sırlar',
      ),
      ritualLine: LocalizedText(
        fa: 'فنجانت را وارونه کن و یک عکس بگیر.',
        en: 'Turn your cup over and take a photo.',
        ar: 'اقلب فنجانك والتقط صورة.',
        tr: 'Fincanını ters çevir ve bir fotoğraf çek.',
      ),
      cta: LocalizedText(
        fa: 'فنجان را بخوان',
        en: 'Read the cup',
        ar: 'اقرأ الفنجان',
        tr: 'Fincanı oku',
      ),
      availability: FortuneAvailability.available,
      pace: RitualPace(
        enter: Duration(milliseconds: 500),
        step: Duration(milliseconds: 150),
      ),
    ),
  ];

  static final List<FortuneDefinition> _extended = [
    _intent(
      'abjad',
      'فال ابجد',
      'حروف و اعداد',
      _gold,
      'نامت و نیتت را در دل بیاور.',
      'Bring your name and intention to heart.',
      'حسابِ ابجد را بگشا',
      'Open the abjad reckoning',
      titleEn: 'Abjad',
      titleAr: 'فأل الأبجد',
      titleTr: 'Ebced Falı',
      subEn: 'Letters and numbers',
      subAr: 'حروف وأرقام',
      subTr: 'Harfler ve sayılar',
      ritualAr: 'أحضر اسمك ونيّتك إلى قلبك.',
      ritualTr: 'Adını ve niyetini kalbine getir.',
      ctaAr: 'افتح حساب الأبجد',
      ctaTr: 'Ebced hesabını aç',
    ),
    _twoNames(
      'marriage',
      'فال ازدواج',
      'آیندهٔ ازدواج',
      _rose,
      'دو نام را بیاور؛ پیوندشان را می‌خوانیم.',
      'Bring both names; we read their bond.',
      'آیندهٔ پیوند را ببین',
      'See the future of the bond',
      titleEn: 'Marriage',
      titleAr: 'فأل الزواج',
      titleTr: 'Evlilik Falı',
      subEn: 'The future of a union',
      subAr: 'مستقبل الزواج',
      subTr: 'Evliliğin geleceği',
      ritualAr: 'أحضر الاسمين؛ نقرأ رابطتهما.',
      ritualTr: 'İki ismi getir; bağlarını okuyalım.',
      ctaAr: 'اعرض مستقبل الرابطة',
      ctaTr: 'Bağın geleceğini gör',
    ),
    _intent(
      'child',
      'فال فرزند',
      'فرزند داری؟',
      _magenta,
      'دست بر دل بگذار و به فردای خانه فکر کن.',
      'Rest a hand on your heart; think of tomorrow.',
      'فال فرزند را باز کن',
      'Open the child reading',
      titleEn: 'Child',
      titleAr: 'فأل الذرّية',
      titleTr: 'Çocuk Falı',
      subEn: 'A child ahead?',
      subAr: 'هل من ذرّية؟',
      subTr: 'Çocuk var mı?',
      ritualAr: 'ضع يدك على قلبك وفكّر في غد البيت.',
      ritualTr: 'Elini kalbine koy, evin yarınını düşün.',
      ctaAr: 'افتح فأل الذرّية',
      ctaTr: 'Çocuk falını aç',
    ),
    _intent(
      'friendship',
      'فال دوستی',
      'دوستانِ واقعی',
      _teal,
      'چهرهٔ دوستانت را از دل بگذران.',
      'Let your friends pass through your heart.',
      'حقیقتِ دوستی را ببین',
      'See the truth of friendship',
      titleEn: 'Friendship',
      titleAr: 'فأل الصداقة',
      titleTr: 'Dostluk Falı',
      subEn: 'True friends',
      subAr: 'الأصدقاء الحقيقيون',
      subTr: 'Gerçek dostlar',
      ritualAr: 'أمرر وجوه أصدقائك على قلبك.',
      ritualTr: 'Dostlarının yüzünü kalbinden geçir.',
      ctaAr: 'اعرض حقيقة الصداقة',
      ctaTr: 'Dostluğun gerçeğini gör',
    ),
    _intent(
      'separation',
      'فال جدایی',
      'پایانِ رابطه؟',
      _blue,
      'آنچه را رها می‌کنی، آرام به یاد بیاور.',
      'Gently recall what you are letting go.',
      'مسیرِ جدایی را بخوان',
      'Read the parting path',
      titleEn: 'Parting',
      titleAr: 'فأل الفراق',
      titleTr: 'Ayrılık Falı',
      subEn: 'An ending near?',
      subAr: 'نهاية العلاقة؟',
      subTr: 'İlişkinin sonu mu?',
      ritualAr: 'تذكّر بهدوء ما أنت تاركه.',
      ritualTr: 'Bıraktığın şeyi usulca hatırla.',
      ctaAr: 'اقرأ درب الفراق',
      ctaTr: 'Ayrılık yolunu oku',
    ),
    _twoNames(
      'reconcile',
      'فال آشتی',
      'بازگشتِ او',
      _rose,
      'دو نام، یک دلِ چشم‌به‌راه.',
      'Two names, one waiting heart.',
      'راهِ آشتی را ببین',
      'See the way back',
      titleEn: 'Reunion',
      titleAr: 'فأل الصلح',
      titleTr: 'Barışma Falı',
      subEn: 'Their return',
      subAr: 'عودته إليك',
      subTr: 'Onun dönüşü',
      ritualAr: 'اسمان، وقلب واحد ينتظر.',
      ritualTr: 'İki isim, bekleyen tek yürek.',
      ctaAr: 'اعرض طريق الصلح',
      ctaTr: 'Barışma yolunu gör',
    ),
    _intent(
      'name',
      'فال اسم',
      'رازِ نامت',
      _violet,
      'نامت را در دل صدا بزن.',
      'Call your name within.',
      'رازِ نامت را بگشا',
      'Unfold the secret of your name',
      titleEn: 'Name',
      titleAr: 'فأل الاسم',
      titleTr: 'İsim Falı',
      subEn: 'The secret of your name',
      subAr: 'سرّ اسمك',
      subTr: 'Adının sırrı',
      ritualAr: 'نادِ اسمك في قلبك.',
      ritualTr: 'Adını içinden çağır.',
      ctaAr: 'اكشف سرّ اسمك',
      ctaTr: 'Adının sırrını aç',
    ),
    _intent(
      'job',
      'فال شغل',
      'آیندهٔ کاری',
      _emerald,
      'به راهی که می‌روی فکر کن.',
      'Think of the road you walk.',
      'آیندهٔ کاری‌ات را ببین',
      'See your working future',
      titleEn: 'Career',
      titleAr: 'فأل العمل',
      titleTr: 'İş Falı',
      subEn: 'Your working future',
      subAr: 'مستقبلك المهني',
      subTr: 'Kariyerinin geleceği',
      ritualAr: 'فكّر في الطريق الذي تسلكه.',
      ritualTr: 'Yürüdüğün yolu düşün.',
      ctaAr: 'اعرض مستقبلك المهني',
      ctaTr: 'İş geleceğini gör',
    ),
    _intent(
      'money',
      'فال مالی',
      'ثروت و پول',
      _amber,
      'به روزی و دارایی‌ات نیت کن.',
      'Set an intention for your provision.',
      'فال مالی را باز کن',
      'Open the wealth reading',
      titleEn: 'Wealth',
      titleAr: 'فأل الرزق',
      titleTr: 'Bolluk Falı',
      subEn: 'Wealth and provision',
      subAr: 'المال والرزق',
      subTr: 'Bolluk ve para',
      ritualAr: 'انوِ نيّتك لرزقك ومالك.',
      ritualTr: 'Rızkın ve varlığın için niyet et.',
      ctaAr: 'افتح فأل الرزق',
      ctaTr: 'Bolluk falını aç',
    ),
    _intent(
      'travel',
      'فال سفر',
      'سفر در راه؟',
      _sky,
      'مقصدی را که در سر داری تصور کن.',
      'Picture the destination on your mind.',
      'راهِ سفر را بخوان',
      'Read the road ahead',
      titleEn: 'Journey',
      titleAr: 'فأل السفر',
      titleTr: 'Yolculuk Falı',
      subEn: 'A journey ahead?',
      subAr: 'سفر في الطريق؟',
      subTr: 'Yolda bir yolculuk mu?',
      ritualAr: 'تخيّل الوجهة التي في بالك.',
      ritualTr: 'Aklındaki hedefi gözünde canlandır.',
      ctaAr: 'اقرأ طريق السفر',
      ctaTr: 'Önündeki yolu oku',
    ),
    _intent(
      'future',
      'فال آینده',
      'در انتظارِ من',
      _violet,
      'چشم‌هایت را ببند و به فردا بنگر.',
      'Close your eyes and look to tomorrow.',
      'پردهٔ آینده را کنار بزن',
      'Draw back the veil',
      titleEn: 'Future',
      titleAr: 'فأل المستقبل',
      titleTr: 'Gelecek Falı',
      subEn: 'Waiting for me',
      subAr: 'ما ينتظرني',
      subTr: 'Beni ne bekliyor',
      ritualAr: 'أغمض عينيك وانظر إلى الغد.',
      ritualTr: 'Gözlerini kapat, yarına bak.',
      ctaAr: 'أزح ستار المستقبل',
      ctaTr: 'Gelecek perdesini arala',
    ),
    _intent(
      'message',
      'فال پیام',
      'پیامی در راه',
      _turq,
      'دلت منتظرِ کدام خبر است؟',
      'Which news is your heart waiting for?',
      'پیامت را بگیر',
      'Receive your message',
      titleEn: 'Message',
      titleAr: 'فأل الرسالة',
      titleTr: 'Mesaj Falı',
      subEn: 'A message coming',
      subAr: 'رسالة في الطريق',
      subTr: 'Yolda bir mesaj',
      ritualAr: 'أي خبر ينتظره قلبك؟',
      ritualTr: 'Kalbin hangi haberi bekliyor?',
      ctaAr: 'استلم رسالتك',
      ctaTr: 'Mesajını al',
    ),
    _intent(
      'intention',
      'فال نیت',
      'نیتِ قلبی',
      _gold,
      'نیتت را خالص کن؛ همین کافی‌ست.',
      'Make the intention pure; that is enough.',
      'فال نیت را باز کن',
      'Open the intention reading',
      titleEn: 'Intention',
      titleAr: 'فأل النيّة',
      titleTr: 'Niyet Falı',
      subEn: 'The heart\'s intent',
      subAr: 'نيّة القلب',
      subTr: 'Kalbin niyeti',
      ritualAr: 'أخلص نيّتك؛ هذا يكفي.',
      ritualTr: 'Niyetini arındır; bu yeter.',
      ctaAr: 'افتح فأل النيّة',
      ctaTr: 'Niyet falını aç',
    ),
    _intent(
      'yesno',
      'بله یا خیر',
      'پاسخِ سریع',
      _amber,
      'پرسشت را کوتاه و روشن در دل بگو.',
      'Ask it short and clear, within.',
      'بله یا خیر را ببین',
      'See yes or no',
      offering: FortuneOffering.chips,
      chips: const [
        LocalizedText(
          fa: 'آیا این‌طور می‌شود؟',
          en: 'Will it turn out so?',
          ar: 'هل سيكون الأمر كذلك؟',
          tr: 'Böyle olacak mı?',
        ),
        LocalizedText(
          fa: 'آیا پیش بروم؟',
          en: 'Should I go ahead?',
          ar: 'هل أمضي قدمًا؟',
          tr: 'İlerleyeyim mi?',
        ),
        LocalizedText(
          fa: 'آیا او همان است؟',
          en: 'Is this the one?',
          ar: 'هل هو الشخص المنشود؟',
          tr: 'O kişi o mu?',
        ),
      ],
      titleEn: 'Yes or No',
      titleAr: 'نعم أم لا',
      titleTr: 'Evet ya da Hayır',
      subEn: 'A quick answer',
      subAr: 'جواب سريع',
      subTr: 'Hızlı bir cevap',
      ritualAr: 'قل سؤالك في قلبك قصيرًا وواضحًا.',
      ritualTr: 'Sorunu içinden kısa ve net söyle.',
      ctaAr: 'اعرض نعم أم لا',
      ctaTr: 'Evet mi hayır mı gör',
    ),
    _intent(
      'luckynumber',
      'عدد شانس',
      'عددِ خوش‌یمن',
      _teal,
      'به بختت اعتماد کن.',
      'Trust your luck.',
      'عددِ شانست را ببین',
      'See your lucky number',
      offering: FortuneOffering.chips,
      chips: const [
        LocalizedText(
          fa: 'برای امروز',
          en: 'For today',
          ar: 'لهذا اليوم',
          tr: 'Bugün için',
        ),
        LocalizedText(
          fa: 'برای این هفته',
          en: 'For this week',
          ar: 'لهذا الأسبوع',
          tr: 'Bu hafta için',
        ),
        LocalizedText(
          fa: 'برای این ماه',
          en: 'For this month',
          ar: 'لهذا الشهر',
          tr: 'Bu ay için',
        ),
      ],
      titleEn: 'Lucky Number',
      titleAr: 'رقم الحظ',
      titleTr: 'Şans Sayısı',
      subEn: 'Your auspicious number',
      subAr: 'رقمك الميمون',
      subTr: 'Uğurlu sayın',
      ritualAr: 'ثق بحظّك.',
      ritualTr: 'Şansına güven.',
      ctaAr: 'اعرض رقم حظّك',
      ctaTr: 'Şans sayını gör',
    ),
    _intent(
      'luckycolor',
      'رنگ شانس',
      'رنگِ امروز',
      _magenta,
      'امروزت را رنگی تصور کن.',
      'Imagine today in colour.',
      'رنگِ امروزت را ببین',
      'See the colour of today',
      offering: FortuneOffering.colors,
      titleEn: 'Lucky Colour',
      titleAr: 'لون الحظ',
      titleTr: 'Şans Rengi',
      subEn: 'Colour of today',
      subAr: 'لون اليوم',
      subTr: 'Bugünün rengi',
      ritualAr: 'تخيّل يومك ملوّنًا.',
      ritualTr: 'Bugününü renkli hayal et.',
      ctaAr: 'اعرض لون يومك',
      ctaTr: 'Bugünün rengini gör',
    ),
    _intent(
      'luckystone',
      'سنگ شانس',
      'سنگِ متولد',
      _violet,
      'به ماهِ تولدت فکر کن.',
      'Think of your birth month.',
      'سنگِ تو را پیدا کن',
      'Find your stone',
      offering: FortuneOffering.months,
      titleEn: 'Birthstone',
      titleAr: 'حجر الحظ',
      titleTr: 'Şans Taşı',
      subEn: 'Stone of your month',
      subAr: 'حجر مولدك',
      subTr: 'Doğduğun ayın taşı',
      ritualAr: 'فكّر في شهر مولدك.',
      ritualTr: 'Doğduğun ayı düşün.',
      ctaAr: 'اعثر على حجرك',
      ctaTr: 'Taşını bul',
    ),
    _intent(
      'luckyflower',
      'گل شانس',
      'گلِ تو',
      _rose,
      'عطری را که دوست داری به یاد آور.',
      'Recall a scent you love.',
      'گلِ تو را ببین',
      'See your flower',
      titleEn: 'Lucky Flower',
      titleAr: 'زهرة الحظ',
      titleTr: 'Şans Çiçeği',
      subEn: 'Your flower',
      subAr: 'زهرتك',
      subTr: 'Senin çiçeğin',
      ritualAr: 'استحضر عطرًا تحبّه.',
      ritualTr: 'Sevdiğin bir kokuyu hatırla.',
      ctaAr: 'اعرض زهرتك',
      ctaTr: 'Çiçeğini gör',
    ),
    _intent(
      'dailytalisman',
      'طلسم روزانه',
      'حفاظت و انرژی',
      _amber,
      'نیتِ محافظت کن.',
      'Set an intention of protection.',
      'طلسمِ امروز را بگیر',
      'Take the talisman of today',
      titleEn: 'Daily Talisman',
      titleAr: 'طلسم اليوم',
      titleTr: 'Günün Tılsımı',
      subEn: 'Protection and energy',
      subAr: 'حماية وطاقة',
      subTr: 'Koruma ve enerji',
      ritualAr: 'انوِ نيّة الحماية.',
      ritualTr: 'Korunma niyeti tut.',
      ctaAr: 'خذ طلسم اليوم',
      ctaTr: 'Günün tılsımını al',
    ),
    _intent(
      'lots',
      'فال قرعه',
      'قرعه و شانس',
      _copper,
      'نیت کن؛ قرعه به نامِ که می‌افتد؟',
      'Set your intention; whose lot will it be?',
      'قرعه را بینداز',
      'Cast the lot',
      titleEn: 'Lots',
      titleAr: 'فأل القرعة',
      titleTr: 'Kura Falı',
      subEn: 'Lots and luck',
      subAr: 'قرعة وحظّ',
      subTr: 'Kura ve şans',
      ritualAr: 'انوِ؛ باسم من ستقع القرعة؟',
      ritualTr: 'Niyet et; kura kimin adına düşecek?',
      ctaAr: 'ألقِ القرعة',
      ctaTr: 'Kurayı çek',
    ),
    _intent(
      'birthmonth',
      'ماه تولد',
      'طالع و شخصیت',
      _violet,
      'ماهِ تولدت را در دل بگو.',
      'Say your birth month within.',
      'طالعِ ماهت را ببین',
      'See the sign of your month',
      offering: FortuneOffering.months,
      titleEn: 'Birth Month',
      titleAr: 'شهر الميلاد',
      titleTr: 'Doğum Ayı',
      subEn: 'Sign and character',
      subAr: 'الطالع والشخصية',
      subTr: 'Yıldızın ve karakterin',
      ritualAr: 'قل شهر ميلادك في قلبك.',
      ritualTr: 'Doğum ayını içinden söyle.',
      ctaAr: 'اعرض طالع شهرك',
      ctaTr: 'Ayının yıldızını gör',
    ),
    _intent(
      'daily',
      'فال روزانه',
      'ویژهٔ امروز',
      _gold,
      'امروزت را به بخت بسپار.',
      'Entrust today to fortune.',
      'فالِ امروز را باز کن',
      'Open the daily reading',
      titleEn: 'Daily',
      titleAr: 'فأل اليوم',
      titleTr: 'Günlük Fal',
      subEn: 'Made for today',
      subAr: 'خاص بهذا اليوم',
      subTr: 'Bugüne özel',
      ritualAr: 'سلّم يومك للبخت.',
      ritualTr: 'Bugününü bahta bırak.',
      ctaAr: 'افتح فأل اليوم',
      ctaTr: 'Günün falını aç',
    ),
    _intent(
      'universe',
      'فال کائنات',
      'پیامِ جهان',
      _violet,
      'پیامت را به کائنات بسپار.',
      'Entrust your message to the universe.',
      'پاسخِ کائنات را بشنو',
      'Hear the universe answer',
      titleEn: 'Universe',
      titleAr: 'فأل الكون',
      titleTr: 'Evren Falı',
      subEn: 'Message of the cosmos',
      subAr: 'رسالة الكون',
      subTr: 'Evrenin mesajı',
      ritualAr: 'سلّم رسالتك إلى الكون.',
      ritualTr: 'Mesajını evrene emanet et.',
      ctaAr: 'اسمع جواب الكون',
      ctaTr: 'Evrenin cevabını duy',
    ),
    _intent(
      'tea',
      'فال چای',
      'برگ‌های چای',
      _jade,
      'فنجانِ چای را در خیال گرم بگیر.',
      'Hold a warm cup in your mind.',
      'برگ‌های چای را بخوان',
      'Read the tea leaves',
      titleEn: 'Tea Leaves',
      titleAr: 'قراءة الشاي',
      titleTr: 'Çay Falı',
      subEn: 'The tea leaves',
      subAr: 'أوراق الشاي',
      subTr: 'Çay yaprakları',
      ritualAr: 'أمسك في خيالك فنجانًا دافئًا.',
      ritualTr: 'Zihninde sıcak bir fincan tut.',
      ctaAr: 'اقرأ أوراق الشاي',
      ctaTr: 'Çay yapraklarını oku',
    ),
    _intent(
      'candle',
      'فال شمع',
      'نور و انرژی',
      _amber,
      'شمعی در دلت روشن کن.',
      'Light a candle within.',
      'رقصِ شعله را بخوان',
      'Read the dancing flame',
      titleEn: 'Candle',
      titleAr: 'فأل الشمعة',
      titleTr: 'Mum Falı',
      subEn: 'Light and energy',
      subAr: 'نور وطاقة',
      subTr: 'Işık ve enerji',
      ritualAr: 'أشعل شمعة في قلبك.',
      ritualTr: 'İçinde bir mum yak.',
      ctaAr: 'اقرأ رقصة اللهب',
      ctaTr: 'Alevin dansını oku',
    ),
    _intent(
      'mirror',
      'فال آینه',
      'آینهٔ آینده',
      _sky,
      'در آینهٔ دل به خودت نگاه کن.',
      'Look at yourself in the heart-mirror.',
      'رازِ آینه را ببین',
      'See the mirror secret',
      titleEn: 'Mirror',
      titleAr: 'فأل المرآة',
      titleTr: 'Ayna Falı',
      subEn: 'Mirror of the future',
      subAr: 'مرآة المستقبل',
      subTr: 'Geleceğin aynası',
      ritualAr: 'انظر إلى نفسك في مرآة القلب.',
      ritualTr: 'Kalbinin aynasında kendine bak.',
      ctaAr: 'اعرض سرّ المرآة',
      ctaTr: 'Aynanın sırrını gör',
    ),
    _intent(
      'lenormand',
      'فال لنورمان',
      'کارت‌های لنورمان',
      _turq,
      'پرسشت را به کارت‌ها بسپار.',
      'Give your question to the cards.',
      'کارت‌های لنورمان را بچین',
      'Lay the Lenormand cards',
      titleEn: 'Lenormand',
      titleAr: 'اللينورماند',
      titleTr: 'Lenormand',
      subEn: 'The Lenormand cards',
      subAr: 'بطاقات اللينورماند',
      subTr: 'Lenormand kartları',
      ritualAr: 'سلّم سؤالك إلى البطاقات.',
      ritualTr: 'Sorunu kartlara bırak.',
      ctaAr: 'رتّب بطاقات اللينورماند',
      ctaTr: 'Lenormand kartlarını diz',
    ),
    _intent(
      'rune',
      'فال رون',
      'حروفِ باستان',
      _copper,
      'به حروفِ کهن نیت کن.',
      'Set your intention on the old letters.',
      'رون‌ها را بینداز',
      'Cast the runes',
      titleEn: 'Runes',
      titleAr: 'فأل الرونية',
      titleTr: 'Rün Falı',
      subEn: 'The ancient letters',
      subAr: 'الحروف القديمة',
      subTr: 'Kadim harfler',
      ritualAr: 'انوِ نيّتك على الحروف القديمة.',
      ritualTr: 'Kadim harflere niyet tut.',
      ctaAr: 'ألقِ الرونات',
      ctaTr: 'Rünleri at',
    ),
    _intent(
      'cards',
      'فال کارتی',
      'کارت‌های اوراکل',
      _teal,
      'کارتی را در دل انتخاب کن.',
      'Choose a card within.',
      'کارتت را برگردان',
      'Turn your card',
      titleEn: 'Oracle Cards',
      titleAr: 'فأل البطاقات',
      titleTr: 'Kart Falı',
      subEn: 'The oracle cards',
      subAr: 'بطاقات الأوراكل',
      subTr: 'Kehanet kartları',
      ritualAr: 'اختر بطاقة في قلبك.',
      ritualTr: 'İçinden bir kart seç.',
      ctaAr: 'اقلب بطاقتك',
      ctaTr: 'Kartını çevir',
    ),
    _intent(
      'quran',
      'فال قرآن',
      'استخارهٔ قرآن',
      _emerald,
      'با دلی آرام استخاره کن.',
      'Seek guidance with a quiet heart.',
      'استخاره را بگشا',
      'Open the istikhara',
      titleEn: 'Istikhara',
      titleAr: 'استخارة القرآن',
      titleTr: 'İstihare',
      subEn: 'Quranic istikhara',
      subAr: 'الاستخارة بالقرآن',
      subTr: 'Kur\'an istiharesi',
      ritualAr: 'استخر بقلب مطمئن.',
      ritualTr: 'Sakin bir kalple istihare et.',
      ctaAr: 'افتح الاستخارة',
      ctaTr: 'İstihareyi aç',
    ),
    _intent(
      'tasbih',
      'فال تسبیح',
      'دانه‌های تسبیح',
      _jade,
      'دانه‌ها را در دل بشمار و نیت کن.',
      'Count the beads within and intend.',
      'تسبیح را بگردان',
      'Turn the prayer beads',
      titleEn: 'Prayer Beads',
      titleAr: 'فأل المسبحة',
      titleTr: 'Tesbih Falı',
      subEn: 'The tasbih beads',
      subAr: 'حبّات المسبحة',
      subTr: 'Tesbih taneleri',
      ritualAr: 'عدّ الحبّات في قلبك وانوِ.',
      ritualTr: 'Taneleri içinden say ve niyet et.',
      ctaAr: 'أدر المسبحة',
      ctaTr: 'Tesbihi çevir',
    ),
    _intent(
      'angel',
      'پیام فرشتگان',
      'پیامِ فرشته',
      _sky,
      'چشم‌هایت را ببند؛ فرشته‌ات نزدیک است.',
      'Close your eyes; your angel is near.',
      'پیامِ فرشته را بگیر',
      'Receive the angel message',
      titleEn: 'Angel Message',
      titleAr: 'رسالة الملائكة',
      titleTr: 'Melek Mesajı',
      subEn: 'Your angel\'s word',
      subAr: 'رسالة ملاكك',
      subTr: 'Meleğinin mesajı',
      ritualAr: 'أغمض عينيك؛ ملاكك قريب.',
      ritualTr: 'Gözlerini kapat; meleğin yakında.',
      ctaAr: 'استلم رسالة الملاك',
      ctaTr: 'Melek mesajını al',
    ),
    _intent(
      'spiritanimal',
      'حیوان روح',
      'حیوانِ روحِ تو',
      _copper,
      'به جانِ وحشیِ درونت گوش بده.',
      'Listen to the wild soul within.',
      'حیوانِ روحت را بیاب',
      'Find your spirit animal',
      titleEn: 'Spirit Animal',
      titleAr: 'حيوان الروح',
      titleTr: 'Ruh Hayvanı',
      subEn: 'Your spirit animal',
      subAr: 'حيوان روحك',
      subTr: 'Senin ruh hayvanın',
      ritualAr: 'أصغِ إلى الروح البرّية في داخلك.',
      ritualTr: 'İçindeki yabanıl ruhu dinle.',
      ctaAr: 'اعثر على حيوان روحك',
      ctaTr: 'Ruh hayvanını bul',
    ),
    _intent(
      'meditation',
      'مدیتیشن',
      'نیت‌گذاری',
      _teal,
      'سه نفسِ عمیق؛ سپس نیت کن.',
      'Three deep breaths; then intend.',
      'نیت‌گذاری را آغاز کن',
      'Begin the intention',
      titleEn: 'Meditation',
      titleAr: 'التأمّل',
      titleTr: 'Meditasyon',
      subEn: 'Setting intention',
      subAr: 'غرس النيّة',
      subTr: 'Niyet koyma',
      ritualAr: 'ثلاثة أنفاس عميقة؛ ثم انوِ.',
      ritualTr: 'Üç derin nefes; sonra niyet et.',
      ctaAr: 'ابدأ غرس النيّة',
      ctaTr: 'Niyet koymaya başla',
    ),
  ];

  /// Intention fortune with its own ritual voice: each fortune whispers its
  /// own line and names its own act — never a shared template sentence.
  static FortuneDefinition _intent(
    String id,
    String fa,
    String sub,
    Color a,
    String ritualFa,
    String ritualEn,
    String ctaFa,
    String ctaEn, {
    required String titleEn,
    required String titleAr,
    required String titleTr,
    required String subEn,
    required String subAr,
    required String subTr,
    required String ritualAr,
    required String ritualTr,
    required String ctaAr,
    required String ctaTr,
    FortuneOffering offering = FortuneOffering.none,
    List<LocalizedText> chips = const [],
  }) {
    return FortuneDefinition(
      id: id,
      accent: a,
      inputKind: FortuneInputKind.intention,
      title: LocalizedText(fa: fa, en: titleEn, ar: titleAr, tr: titleTr),
      subtitle: LocalizedText(fa: sub, en: subEn, ar: subAr, tr: subTr),
      ritualLine: LocalizedText(
        fa: ritualFa,
        en: ritualEn,
        ar: ritualAr,
        tr: ritualTr,
      ),
      placeholder: const LocalizedText(
        fa: '…یا این‌جا با خودت بگو',
        en: '…or whisper it here',
        ar: '…أو اهمس بها هنا',
        tr: '…ya da burada fısılda',
      ),
      cta: LocalizedText(fa: ctaFa, en: ctaEn, ar: ctaAr, tr: ctaTr),
      pace: _pace,
      offering: offering,
      offeringChips: chips,
    );
  }

  static FortuneDefinition _twoNames(
    String id,
    String fa,
    String sub,
    Color a,
    String ritualFa,
    String ritualEn,
    String ctaFa,
    String ctaEn, {
    required String titleEn,
    required String titleAr,
    required String titleTr,
    required String subEn,
    required String subAr,
    required String subTr,
    required String ritualAr,
    required String ritualTr,
    required String ctaAr,
    required String ctaTr,
  }) {
    return FortuneDefinition(
      id: id,
      accent: a,
      inputKind: FortuneInputKind.twoNames,
      title: LocalizedText(fa: fa, en: titleEn, ar: titleAr, tr: titleTr),
      subtitle: LocalizedText(fa: sub, en: subEn, ar: subAr, tr: subTr),
      ritualLine: LocalizedText(
        fa: ritualFa,
        en: ritualEn,
        ar: ritualAr,
        tr: ritualTr,
      ),
      placeholder: const LocalizedText(
        fa: 'نامِ نخست',
        en: 'First name',
        ar: 'الاسم الأول',
        tr: 'Birinci isim',
      ),
      placeholderSecond: const LocalizedText(
        fa: 'نامِ دوم',
        en: 'Second name',
        ar: 'الاسم الثاني',
        tr: 'İkinci isim',
      ),
      cta: LocalizedText(fa: ctaFa, en: ctaEn, ar: ctaAr, tr: ctaTr),
      guide: const LocalizedText(
        fa: 'برای این فال، هر دو نام را بنویس.',
        en: 'Write both names for this reading.',
        ar: 'لهذا الفأل، اكتب الاسمين معًا.',
        tr: 'Bu fal için iki ismi de yaz.',
      ),
      maxLength: 60,
      pace: _pace,
    );
  }

  static FortuneDefinition? byId(String id) {
    for (final f in all) {
      if (f.id == id) return f;
    }
    return null;
  }
}
