/** One card of the Petit Lenormand. Meanings are faithful Persian
 *  renderings of the standard traditional keyword meanings (read upright
 *  only — Lenormand has no reversals). */
export interface LenormandCard {
  id: string;
  number: number;
  nameFa: string;
  nameEn: string;
  meaningFa: string;
}

/** The full 36-card deck, in the standard order. Held in code — small and
 *  static, so no database; the draw indexes straight into this array. */
export const LENORMAND_DECK: readonly LenormandCard[] = [
  {
    id: 'lenormand-01',
    number: 1,
    nameFa: 'سوار',
    nameEn: 'Rider',
    meaningFa: 'خبر، پیام، رسیدنِ چیزی، مردِ جوان، حرکت و شتاب',
  },
  {
    id: 'lenormand-02',
    number: 2,
    nameFa: 'شبدر',
    nameEn: 'Clover',
    meaningFa: 'بختِ کوچک، شانس، فرصت، سبک‌دلی، اقبالِ کوتاهِ خوش',
  },
  {
    id: 'lenormand-03',
    number: 3,
    nameFa: 'کشتی',
    nameEn: 'Ship',
    meaningFa: 'سفر، دوری، مسافرت، اشتیاق، داد‌وستدِ دور و ماجرا',
  },
  {
    id: 'lenormand-04',
    number: 4,
    nameFa: 'خانه',
    nameEn: 'House',
    meaningFa: 'خانه، خانواده، ثباتِ خانگی، ملک، سنت و امنیت',
  },
  {
    id: 'lenormand-05',
    number: 5,
    nameFa: 'درخت',
    nameEn: 'Tree',
    meaningFa: 'سلامتی، رشد، ریشه، نیروی زندگی، دوام و سرزندگی',
  },
  {
    id: 'lenormand-06',
    number: 6,
    nameFa: 'ابرها',
    nameEn: 'Clouds',
    meaningFa: 'سردرگمی، تردید، ابهام، دردسرِ پنهان و حال‌وهوای دمدمی',
  },
  {
    id: 'lenormand-07',
    number: 7,
    nameFa: 'مار',
    nameEn: 'Snake',
    meaningFa: 'پیچیدگی، بیراهه، فریب، رقیب، خیانت و اغوا',
  },
  {
    id: 'lenormand-08',
    number: 8,
    nameFa: 'تابوت',
    nameEn: 'Coffin',
    meaningFa: 'پایان، از دست دادن، بسته‌شدن، بیماری، دگرگونی و استراحتِ لازم',
  },
  {
    id: 'lenormand-09',
    number: 9,
    nameFa: 'دسته‌گل',
    nameEn: 'Bouquet',
    meaningFa: 'هدیه، دعوت، زیبایی، شادی، قدردانی و مهربانی',
  },
  {
    id: 'lenormand-10',
    number: 10,
    nameFa: 'داس',
    nameEn: 'Scythe',
    meaningFa: 'بریدنِ ناگهانی، خطر، تصمیمِ تیز، درو و پایانِ ناگهانی',
  },
  {
    id: 'lenormand-11',
    number: 11,
    nameFa: 'شلاق',
    nameEn: 'Whip',
    meaningFa: 'ستیز، تکرار، بگومگو، انضباط و تکاپوی بدنی',
  },
  {
    id: 'lenormand-12',
    number: 12,
    nameFa: 'پرندگان',
    nameEn: 'Birds',
    meaningFa: 'گفت‌وگو، شایعه، دلواپسی، تماس‌ها و یک زوج',
  },
  {
    id: 'lenormand-13',
    number: 13,
    nameFa: 'کودک',
    nameEn: 'Child',
    meaningFa: 'آغازِ تازه، معصومیت، چیزی کوچک، کودک، بی‌تجربگی',
  },
  {
    id: 'lenormand-14',
    number: 14,
    nameFa: 'روباه',
    nameEn: 'Fox',
    meaningFa: 'زیرکی، منفعتِ خود، کار، بدگمانی، تدبیر و احتیاط',
  },
  {
    id: 'lenormand-15',
    number: 15,
    nameFa: 'خرس',
    nameEn: 'Bear',
    meaningFa: 'قدرت، توان، اقتدار، امورِ مالی، رئیس و محافظت',
  },
  {
    id: 'lenormand-16',
    number: 16,
    nameFa: 'ستاره',
    nameEn: 'Star',
    meaningFa: 'امید، راهنمایی، الهام، معنویت، وضوح و اقبالِ نیک',
  },
  {
    id: 'lenormand-17',
    number: 17,
    nameFa: 'لک‌لک',
    nameEn: 'Stork',
    meaningFa: 'تغییر، جابه‌جایی، بهبود، نقلِ مکان، بارداری و گذار',
  },
  {
    id: 'lenormand-18',
    number: 18,
    nameFa: 'سگ',
    nameEn: 'Dog',
    meaningFa: 'دوستی، وفاداری، اعتماد، همراه، پشتیبانی و صداقت',
  },
  {
    id: 'lenormand-19',
    number: 19,
    nameFa: 'برج',
    nameEn: 'Tower',
    meaningFa: 'اقتدار، نهادها، انزوا، جاه‌طلبی، مرز و تنهایی',
  },
  {
    id: 'lenormand-20',
    number: 20,
    nameFa: 'باغ',
    nameEn: 'Garden',
    meaningFa: 'زندگیِ اجتماعی، گردهمایی، اجتماع، شبکه‌سازی و آبرو',
  },
  {
    id: 'lenormand-21',
    number: 21,
    nameFa: 'کوه',
    nameEn: 'Mountain',
    meaningFa: 'مانع، تأخیر، سدّ، چالش و مخالفتِ سرسخت',
  },
  {
    id: 'lenormand-22',
    number: 22,
    nameFa: 'چهارراه',
    nameEn: 'Crossroads',
    meaningFa: 'انتخاب، تصمیم، گزینه‌ها، راه‌های چندگانه و دوراهیِ پیشِ رو',
  },
  {
    id: 'lenormand-23',
    number: 23,
    nameFa: 'موش‌ها',
    nameEn: 'Mice',
    meaningFa: 'زیان، فرسایش، نگرانی، دزدی، تنش و افولِ تدریجی',
  },
  {
    id: 'lenormand-24',
    number: 24,
    nameFa: 'قلب',
    nameEn: 'Heart',
    meaningFa: 'عشق، دلدادگی، شور، مهر و کامرواییِ عاطفی',
  },
  {
    id: 'lenormand-25',
    number: 25,
    nameFa: 'حلقه',
    nameEn: 'Ring',
    meaningFa: 'تعهد، قرارداد، شراکت، پیمان، چرخه و ازدواج',
  },
  {
    id: 'lenormand-26',
    number: 26,
    nameFa: 'کتاب',
    nameEn: 'Book',
    meaningFa: 'راز، دانش، آموزش، اطلاعاتِ پنهان و ناشناخته',
  },
  {
    id: 'lenormand-27',
    number: 27,
    nameFa: 'نامه',
    nameEn: 'Letter',
    meaningFa: 'سند، ارتباطِ نوشتاری، پیام، خبر و کاغذبازی',
  },
  {
    id: 'lenormand-28',
    number: 28,
    nameFa: 'مرد',
    nameEn: 'Man',
    meaningFa: 'مردِ صاحب‌نیت، مردی مهم، مردانگی یا شریک',
  },
  {
    id: 'lenormand-29',
    number: 29,
    nameFa: 'زن',
    nameEn: 'Woman',
    meaningFa: 'زنِ صاحب‌نیت، زنی مهم، زنانگی یا شریک',
  },
  {
    id: 'lenormand-30',
    number: 30,
    nameFa: 'سوسن',
    nameEn: 'Lily',
    meaningFa: 'آرامش، پختگی، خرد، حسِّ لطیف، بازنشستگی و پاکی',
  },
  {
    id: 'lenormand-31',
    number: 31,
    nameFa: 'خورشید',
    nameEn: 'Sun',
    meaningFa: 'کامیابی، سرزندگی، شادی، انرژی، دستاورد و گرما',
  },
  {
    id: 'lenormand-32',
    number: 32,
    nameFa: 'ماه',
    nameEn: 'Moon',
    meaningFa: 'احساس، شهود، آبرو، شهرت، به‌رسمیت‌شناخته‌شدن و ناخودآگاه',
  },
  {
    id: 'lenormand-33',
    number: 33,
    nameFa: 'کلید',
    nameEn: 'Key',
    meaningFa: 'راه‌حل، یقین، اهمیت، گشایش، سرنوشت و آری',
  },
  {
    id: 'lenormand-34',
    number: 34,
    nameFa: 'ماهی',
    nameEn: 'Fish',
    meaningFa: 'پول، ثروت، فراوانی، کسب‌وکار، منابع و استقلال',
  },
  {
    id: 'lenormand-35',
    number: 35,
    nameFa: 'لنگر',
    nameEn: 'Anchor',
    meaningFa: 'ثبات، امنیت، کار، پشتکار و تعهدِ بلندمدت',
  },
  {
    id: 'lenormand-36',
    number: 36,
    nameFa: 'صلیب',
    nameEn: 'Cross',
    meaningFa: 'بار، رنج، وظیفه، سرنوشت، سختی و آزمونِ معنوی',
  },
];
