export type TarotArcana = 'major' | 'minor';
export type TarotSuit = 'wands' | 'cups' | 'swords' | 'pentacles';

/** One card of the Rider-Waite-Smith deck. Meanings are faithful Persian
 *  renderings of Waite's Pictorial Key divinatory keywords (public domain). */
export interface TarotCard {
  id: string;
  arcana: TarotArcana;
  suit: TarotSuit | null;
  nameFa: string;
  nameEn: string;
  uprightFa: string;
  reversedFa: string;
}

/** The full 78-card deck, in a fixed order. Held in code — small and static,
 *  so no database or migration; the draw indexes straight into this array. */
export const TAROT_DECK: readonly TarotCard[] = [
  {
    id: 'major-00',
    arcana: 'major',
    suit: null,
    nameFa: 'دیوانه',
    nameEn: 'The Fool',
    uprightFa: 'آغازِ بی‌پروا و جهش به ناشناخته، بی‌خیالی، سرمستی، شور، معصومیتِ ماجراجو',
    reversedFa: 'غفلت، بی‌دقتی، بی‌تفاوتی، تردید، پوچی، خودبینی',
  },
  {
    id: 'major-01',
    arcana: 'major',
    suit: null,
    nameFa: 'شعبده‌باز',
    nameEn: 'The Magician',
    uprightFa: 'مهارت، اراده، اعتمادِ به‌نفس، تدبیر، چیرگی بر موقعیت',
    reversedFa: 'ارادهٔ سوءاستفاده‌شده، فریب، آشفتگی، بی‌آبرویی، قدرتِ بدفرجام',
  },
  {
    id: 'major-02',
    arcana: 'major',
    suit: null,
    nameFa: 'کاهنهٔ اعظم',
    nameEn: 'The High Priestess',
    uprightFa: 'راز، رمز، شهود، سکوت، حکمتِ نهان، آیندهٔ پوشیده',
    reversedFa: 'شور و شهوتِ سطحی، خودپسندی، دانشِ ظاهری، نیّتِ پنهان',
  },
  {
    id: 'major-03',
    arcana: 'major',
    suit: null,
    nameFa: 'امپراتریس',
    nameEn: 'The Empress',
    uprightFa: 'باروری، فراوانی، آفرینش، آغاز، آسایشِ مادی، پرورش',
    reversedFa: 'روشن‌شدنِ گره‌ها و شادیِ همگانی، اما گاه دودلی و نازایی',
  },
  {
    id: 'major-04',
    arcana: 'major',
    suit: null,
    nameFa: 'امپراتور',
    nameEn: 'The Emperor',
    uprightFa: 'ثبات، قدرت، اقتدار، پشتیبانی، تحقق، خرد و اراده',
    reversedFa: 'مهربانیِ بیش‌ازحد یا از دست رفتنِ اقتدار، سدّ و ناپختگی',
  },
  {
    id: 'major-05',
    arcana: 'major',
    suit: null,
    nameFa: 'کاهن اعظم',
    nameEn: 'The Hierophant',
    uprightFa: 'پیوند، برکت، الهام، سنتِ معنوی، مردِ مشورت',
    reversedFa: 'تفاهم و آشتی، اما ضعف، مهربانیِ افراطی، شکستنِ قاعده و آزادیِ تازه',
  },
  {
    id: 'major-06',
    arcana: 'major',
    suit: null,
    nameFa: 'دلدادگان',
    nameEn: 'The Lovers',
    uprightFa: 'کشش، عشق، زیبایی، هماهنگی، آزمونی که پشتِ سر گذاشته می‌شود، انتخابِ دل',
    reversedFa: 'شکست، نقشهٔ نسنجیده، پیوندِ برهم‌خورده، ستیز، ناهماهنگی',
  },
  {
    id: 'major-07',
    arcana: 'major',
    suit: null,
    nameFa: 'ارابه',
    nameEn: 'The Chariot',
    uprightFa: 'پیروزی، توفیق، پشتوانه، خویشتن‌داری، پیش‌رویِ مصمم',
    reversedFa: 'آشوب، ستیز، دعوا، شکست، از دست رفتنِ مهار و جهت',
  },
  {
    id: 'major-08',
    arcana: 'major',
    suit: null,
    nameFa: 'قدرت',
    nameEn: 'Strength',
    uprightFa: 'نیرو، دلاوری، شجاعت، بزرگواری، کامیابیِ کامل، چیرگیِ درونی',
    reversedFa: 'زورگویی، سوءاستفاده از قدرت، ضعف، ناسازگاری، تردید به خود',
  },
  {
    id: 'major-09',
    arcana: 'major',
    suit: null,
    nameFa: 'راهب',
    nameEn: 'The Hermit',
    uprightFa: 'احتیاط، درون‌نگری، تنهایی، جست‌وجوی درونی، تأمل',
    reversedFa: 'پنهان‌کاری، سیاست، ترس، احتیاطِ بی‌جا، انزوای ناخواسته',
  },
  {
    id: 'major-10',
    arcana: 'major',
    suit: null,
    nameFa: 'چرخ بخت',
    nameEn: 'Wheel of Fortune',
    uprightFa: 'سرنوشت، بخت، کامیابی، اوج‌گیری، اقبال، نقطهٔ چرخش',
    reversedFa: 'فزونی و فراوانی، اما گاه پس‌رفت و مقاومت در برابرِ تغییرِ ناگزیر',
  },
  {
    id: 'major-11',
    arcana: 'major',
    suit: null,
    nameFa: 'عدالت',
    nameEn: 'Justice',
    uprightFa: 'انصاف، درستی، صداقت، قانون، پیروزیِ حقِّ سزاوار',
    reversedFa: 'پیچیدگیِ حقوقی، جانب‌داری، تعصب، سخت‌گیریِ بیش‌ازحد، بی‌عدالتی',
  },
  {
    id: 'major-12',
    arcana: 'major',
    suit: null,
    nameFa: 'مرد آویخته',
    nameEn: 'The Hanged Man',
    uprightFa: 'حکمت، ازخودگذشتگی، تعلیق، بصیرت، تسلیمِ آگاهانه',
    reversedFa: 'خودخواهی، منفعت‌طلبی، ناخواستنِ فداکاری، درجازدن، شهادتِ بی‌جا',
  },
  {
    id: 'major-13',
    arcana: 'major',
    suit: null,
    nameFa: 'مرگ',
    nameEn: 'Death',
    uprightFa: 'پایان، دگرگونی، تحولِ ناگزیر و پاک‌کننده، فروپاشیِ کهنه',
    reversedFa: 'رخوت، خواب، رکود، مقاومت در برابرِ تغییر، امیدِ برباد',
  },
  {
    id: 'major-14',
    arcana: 'major',
    suit: null,
    nameFa: 'اعتدال',
    nameEn: 'Temperance',
    uprightFa: 'میانه‌روی، تعادل، مدیریت، صرفه‌جویی، صبر، سازگاری',
    reversedFa: 'ناسازگاری، ترکیبِ نامیمون، افراط، بی‌تعادلی، زیاده‌روی',
  },
  {
    id: 'major-15',
    arcana: 'major',
    suit: null,
    nameFa: 'شیطان',
    nameEn: 'The Devil',
    uprightFa: 'بندگی، مادیّت، وسوسه، دلبستگیِ مهارناپذیر، شهوت و اجبار',
    reversedFa: 'رهاییِ تدریجی از بند، اما ضعف، کوردلی و خُردیِ نفس',
  },
  {
    id: 'major-16',
    arcana: 'major',
    suit: null,
    nameFa: 'برج',
    nameEn: 'The Tower',
    uprightFa: 'ویرانیِ ناگهانی، بحران، رنج، سقوط، فروریختنِ بنیادِ سست',
    reversedFa: 'همان به‌شکلِ خفیف‌تر، فشار، محدودیت، بلایی که رفع می‌شود',
  },
  {
    id: 'major-17',
    arcana: 'major',
    suit: null,
    nameFa: 'ستاره',
    nameEn: 'The Star',
    uprightFa: 'امید، چشم‌اندازِ روشن، الهام، تجدیدِ ایمان، آرامش',
    reversedFa: 'غرور، خودبزرگ‌بینی، ناتوانی، بدبینی، ایمانِ از دست رفته',
  },
  {
    id: 'major-18',
    arcana: 'major',
    suit: null,
    nameFa: 'ماه',
    nameEn: 'The Moon',
    uprightFa: 'توهم، فریب، ترسِ نهان، ابهام، دشمنانِ پنهان، خطای ادراک',
    reversedFa: 'بی‌ثباتی، اما فرونشستنِ ترس و برطرف‌شدنِ سردرگمی',
  },
  {
    id: 'major-19',
    arcana: 'major',
    suit: null,
    nameFa: 'خورشید',
    nameEn: 'The Sun',
    uprightFa: 'شادی، کامیابی، خرسندی، سرزندگی، دستاورد، سعادت',
    reversedFa: 'همان به‌اندازهٔ کمتر، دلتنگیِ گذرا، کامیابیِ به‌تعویق‌افتاده',
  },
  {
    id: 'major-20',
    arcana: 'major',
    suit: null,
    nameFa: 'داوری',
    nameEn: 'Judgement',
    uprightFa: 'نوزایی، بیداری، حساب‌وکتاب، تغییرِ جایگاه، فرجامِ نیک',
    reversedFa: 'ضعف، دودلی، ترس از داوری، تردید به خود',
  },
  {
    id: 'major-21',
    arcana: 'major',
    suit: null,
    nameFa: 'جهان',
    nameEn: 'The World',
    uprightFa: 'کمال، توفیقِ حتمی، تحقق، پاداش، سفر، تمامیت',
    reversedFa: 'رخوت، درجازدن، ناتمامی، نبودِ نقطهٔ پایان',
  },
  {
    id: 'wands-01',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'آسِ عصاها',
    nameEn: 'Ace of Wands',
    uprightFa: 'آفرینش، ابداع، آغازِ تازه، شور، تولّدِ یک کار',
    reversedFa: 'آغازِ ناکام، افول، شادیِ ابری، لغو، پای‌بستِ سست',
  },
  {
    id: 'wands-02',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'دوی عصاها',
    nameEn: 'Two of Wands',
    uprightFa: 'ثروت، شکوه، فرمانروایی، برنامه‌ریزی، اما گاه بی‌قراری',
    reversedFa: 'شگفتی، دلهره، ترس، از دست رفتنِ ایمان، پس‌رفتِ ناگهانی',
  },
  {
    id: 'wands-03',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'سهٔ عصاها',
    nameEn: 'Three of Wands',
    uprightFa: 'نیروی مستقر، تلاش، تجارت، دوراندیشی، گسترش',
    reversedFa: 'پایانِ سختی‌ها، اما گاه محنت و تأخیر',
  },
  {
    id: 'wands-04',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'چهارِ عصاها',
    nameEn: 'Four of Wands',
    uprightFa: 'آسایش، پناه، آرامش، هماهنگی، جشن و شکوفایی',
    reversedFa: 'همان شکوفایی، اما اندکی لرزان یا در گذار',
  },
  {
    id: 'wands-05',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'پنجِ عصاها',
    nameEn: 'Five of Wands',
    uprightFa: 'رقابت، کشمکش، نبردِ نمایشی، اما گاه سود و بهره',
    reversedFa: 'دعوا، نیرنگ، اختلاف، ستیزی که سرانجام فرومی‌نشیند',
  },
  {
    id: 'wands-06',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'ششِ عصاها',
    nameEn: 'Six of Wands',
    uprightFa: 'پیروزی، خبرِ خوش، تحسینِ همگانی، پیش‌رفت',
    reversedFa: 'بیم، خیانت، بی‌وفایی، تأخیرِ نامعلوم، سقوط از اوج',
  },
  {
    id: 'wands-07',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'هفتِ عصاها',
    nameEn: 'Seven of Wands',
    uprightFa: 'دلاوری، پایداری، دفاع، ایستادگی، کامیابی به‌رغمِ رقیبان',
    reversedFa: 'سرگشتگی، دلواپسی، دودلی، واگذاریِ زمینِ به‌سختی به‌دست‌آمده',
  },
  {
    id: 'wands-08',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'هشتِ عصاها',
    nameEn: 'Eight of Wands',
    uprightFa: 'شتاب، حرکتِ تند، پیش‌رفتِ سریع، تیرهای عشق',
    reversedFa: 'حسادت، دعوای درونی، عذابِ وجدان، تأخیر و کشمکشِ خانگی',
  },
  {
    id: 'wands-09',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'نهٔ عصاها',
    nameEn: 'Nine of Wands',
    uprightFa: 'پایداری در برابرِ مخالفت، تاب‌آوری، آمادگیِ دفاع، شجاعتِ خسته',
    reversedFa: 'مانع، بلا، فرسودگی، بدگمانی، ارادهٔ ازپاافتاده',
  },
  {
    id: 'wands-10',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'دهٔ عصاها',
    nameEn: 'Ten of Wands',
    uprightFa: 'بارِ سنگین، فشار، اما گاه بخت و کامیابی که چون وزنه حمل می‌شود',
    reversedFa: 'دشواری، دسیسه، خیانت، باری که رها یا شانه‌خالی می‌شود',
  },
  {
    id: 'wands-page',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'پیکِ عصاها',
    nameEn: 'Page of Wands',
    uprightFa: 'پیام‌آورِ وفادار، خبرِ خوش، شور، اندیشهٔ نو، کاوش',
    reversedFa: 'خبرِ بد، دودلی، بی‌ثباتی، پس‌رفت، ناپختگیِ بی‌قرار',
  },
  {
    id: 'wands-knight',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'شوالیهٔ عصاها',
    nameEn: 'Knight of Wands',
    uprightFa: 'سفر، ماجرا، انرژی، جابه‌جایی، جوانیِ پرشور',
    reversedFa: 'گسست، وقفه، ناسازگاری، بی‌پروایی، تأخیر',
  },
  {
    id: 'wands-queen',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'ملکهٔ عصاها',
    nameEn: 'Queen of Wands',
    uprightFa: 'زنِ گرم، مطمئن و مهربان، پاک‌دامن، کامیاب در کار',
    reversedFa: 'صرفه‌جو و یاری‌گر، اما گاه حسادت، فریب، بدخُلقی',
  },
  {
    id: 'wands-king',
    arcana: 'minor',
    suit: 'wands',
    nameFa: 'شاهِ عصاها',
    nameEn: 'King of Wands',
    uprightFa: 'مردِ درست‌کار، دوست‌داشتنی و رهبرِ طبیعی، صداقت و پندِ نیک',
    reversedFa: 'نیک اما سخت‌گیر، شتاب‌زده، با انتظارِ بالا',
  },
  {
    id: 'cups-01',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'آسِ جام‌ها',
    nameEn: 'Ace of Cups',
    uprightFa: 'شادی، عشق، خشنودی، فراوانی، دلی لبریز، سرچشمهٔ احساس',
    reversedFa: 'دلِ دروغین، بی‌ثباتی، دگرگونی، احساسِ بسته، تهی‌دستیِ عاطفی',
  },
  {
    id: 'cups-02',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'دوی جام‌ها',
    nameEn: 'Two of Cups',
    uprightFa: 'عشق، دوستی، پیوند، همدلی، هم‌پیمانی، مهر',
    reversedFa: 'ناسازگاری، پیوندِ گسسته، بی‌اعتمادی، بی‌تعادلی',
  },
  {
    id: 'cups-03',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'سهٔ جام‌ها',
    nameEn: 'Three of Cups',
    uprightFa: 'فراوانی، شادمانی، جشن، دوستی، بهبود، فرجامِ خوش',
    reversedFa: 'زیاده‌رویِ در لذت، اما گاه شتاب و شایعه و پایان',
  },
  {
    id: 'cups-04',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'چهارِ جام‌ها',
    nameEn: 'Four of Cups',
    uprightFa: 'دلزدگی، بی‌میلی، ملال، نارضایتی، پیشنهادی نادیده‌گرفته‌شده',
    reversedFa: 'تازگی، پیوندهای نو، بصیرتِ تازه، انگیزهٔ دوباره، پذیرش',
  },
  {
    id: 'cups-05',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'پنجِ جام‌ها',
    nameEn: 'Five of Cups',
    uprightFa: 'غم، افسوس، دلسردی، اما چیزی هنوز باقی است، میراثِ تلخ',
    reversedFa: 'بازگشت، پیوندِ دوباره، بهبود، پذیرش، اما گاه نقشهٔ پوچ',
  },
  {
    id: 'cups-06',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'ششِ جام‌ها',
    nameEn: 'Six of Cups',
    uprightFa: 'خاطره، دلتنگیِ گذشته، کودکی، معصومیت، مهربانی، دیدارِ دوباره',
    reversedFa: 'آینده، نو‌شدن، رو به جلو، آنچه به‌زودی می‌آید',
  },
  {
    id: 'cups-07',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'هفتِ جام‌ها',
    nameEn: 'Seven of Cups',
    uprightFa: 'خیال، توهم، رؤیاپردازی، گزینه‌های بسیار، اما هنوز چیزی حقیقی نیست',
    reversedFa: 'اراده، تصمیم، وضوح، انتخابی قاطع و واقع‌بین',
  },
  {
    id: 'cups-08',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'هشتِ جام‌ها',
    nameEn: 'Eight of Cups',
    uprightFa: 'رهاکردن، پشتِ‌سر گذاشتن، افولِ یک کار، جست‌وجوی معنا',
    reversedFa: 'شادیِ بزرگ و جشن، اما گاه سرگردانی و ترس از رفتن',
  },
  {
    id: 'cups-09',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'نهٔ جام‌ها',
    nameEn: 'Nine of Cups',
    uprightFa: 'خرسندی، خشنودی، بهروزی، کامیابی، برآورده‌شدنِ آرزو',
    reversedFa: 'آرزوی برنیامده، خودپسندیِ خرسند، اما گاه صداقت و آزادی',
  },
  {
    id: 'cups-10',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'دهٔ جام‌ها',
    nameEn: 'Ten of Cups',
    uprightFa: 'خرسندیِ پایدار، عشقِ کامل، خانواده، هماهنگی، خانه',
    reversedFa: 'دلِ دروغین، خانهٔ ازهم‌پاشیده، خشم، ناسازگاری',
  },
  {
    id: 'cups-page',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'پیکِ جام‌ها',
    nameEn: 'Page of Cups',
    uprightFa: 'جوانِ حساس و اهلِ تأمل، خبر، پیام، آغازِ خلاق',
    reversedFa: 'فریب، اغوا، ناپختگیِ عاطفی، دمدمی‌مزاجی، خلاقیتِ بسته',
  },
  {
    id: 'cups-knight',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'شوالیهٔ جام‌ها',
    nameEn: 'Knight of Cups',
    uprightFa: 'آمدن، دعوت، پیشنهاد، عشق، دلبری، گاه پیام‌آور',
    reversedFa: 'نیرنگ، فریب، دورویی، ناواقع‌بینی، دمدمی‌بودن',
  },
  {
    id: 'cups-queen',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'ملکهٔ جام‌ها',
    nameEn: 'Queen of Cups',
    uprightFa: 'زنِ مهربان، صادق، شهودی و دلسوز، همسر و مادرِ آرمانی',
    reversedFa: 'زنی که نباید به او اعتماد کرد، بی‌آبرویی، ناامنیِ عاطفی',
  },
  {
    id: 'cups-king',
    arcana: 'minor',
    suit: 'cups',
    nameFa: 'شاهِ جام‌ها',
    nameEn: 'King of Cups',
    uprightFa: 'مردِ منصفِ کار یا قانون، مهربان، مسئول، خردمند، اهلِ هنر و دانش',
    reversedFa: 'مردِ نادرست و دورو، بی‌عدالتی، رسوایی، زیانِ سنگین',
  },
  {
    id: 'swords-01',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'آسِ شمشیرها',
    nameEn: 'Ace of Swords',
    uprightFa: 'پیروزی، فتح، نیرو، وضوح، قدرتِ ذهن، گشایشِ قاطع',
    reversedFa: 'نیروی سوءاستفاده‌شده و فرجامِ ویران، اما گاه زایش و فزونی',
  },
  {
    id: 'swords-02',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'دوی شمشیرها',
    nameEn: 'Two of Swords',
    uprightFa: 'نیروی متعادل، بن‌بست، آتش‌بس، دودلی، احساسِ مسدود',
    reversedFa: 'فریب، دورویی، بی‌وفایی، اما گاه رویاروییِ با تصمیمِ سخت',
  },
  {
    id: 'swords-03',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'سهٔ شمشیرها',
    nameEn: 'Three of Swords',
    uprightFa: 'دل‌شکستگی، اندوه، جدایی، غیبت، تأخیر، اشک',
    reversedFa: 'آشفتگیِ ذهن، خطا، سردرگمی، بهبودِ کند',
  },
  {
    id: 'swords-04',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'چهارِ شمشیرها',
    nameEn: 'Four of Swords',
    uprightFa: 'آرامش، استراحت، خلوت، بهبودی، مهلتی از کشمکش، تأمل',
    reversedFa: 'فعالیتِ دوباره و احتیاط، اما گاه رکود و فرسودگی',
  },
  {
    id: 'swords-05',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'پنجِ شمشیرها',
    nameEn: 'Five of Swords',
    uprightFa: 'شکست، خواری، بی‌آبرویی، ستیز، پیروزیِ توخالی، خودخواهی',
    reversedFa: 'همان، سوگواری، اما گاه جبران و کنارگذاشتنِ کینه',
  },
  {
    id: 'swords-06',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'ششِ شمشیرها',
    nameEn: 'Six of Swords',
    uprightFa: 'سفر از آب، گذار، پشتِ‌سر گذاشتن، بهبودِ تدریجی',
    reversedFa: 'رکود، گذارِ به‌تعویق‌افتاده، مقاومت، راهِ‌گریزِ بسته',
  },
  {
    id: 'swords-07',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'هفتِ شمشیرها',
    nameEn: 'Seven of Swords',
    uprightFa: 'پنهان‌کاری، زیرکی، نقشه، فریب، طرحی که شاید نگیرد، گریختن',
    reversedFa: 'پندِ نیک، اما گاه تهمت، اعتراف، بازگرداندنِ ربوده‌شده',
  },
  {
    id: 'swords-08',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'هشتِ شمشیرها',
    nameEn: 'Eight of Swords',
    uprightFa: 'بند، محدودیت، بحران، ناتوانی، به‌دام‌افتادن، حصارِ خودساخته',
    reversedFa: 'دشواری و خیانتِ ناگهانی، اما گاه رهایی و آزادی',
  },
  {
    id: 'swords-09',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'نهٔ شمشیرها',
    nameEn: 'Nine of Swords',
    uprightFa: 'دلهره، کابوس، اضطراب، اندوه، رنج، عذابِ وجدان',
    reversedFa: 'بدگمانی، شرم، اما گاه بهبود، امید، دست‌یاری‌خواستن',
  },
  {
    id: 'swords-10',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'دهٔ شمشیرها',
    nameEn: 'Ten of Swords',
    uprightFa: 'ویرانی، پایانِ دردناک، شکست، اشک، ژرفای سیاهی، خیانت',
    reversedFa: 'برتریِ گذرا، بهبود، نوزایی، اما هنوز چیزی پایدار نیست',
  },
  {
    id: 'swords-page',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'پیکِ شمشیرها',
    nameEn: 'Page of Swords',
    uprightFa: 'هوشیاری، مراقبت، کنجکاوی، اندیشهٔ نو، چالاکیِ ذهن',
    reversedFa: 'فریب، رخدادِ ناگهانی، ناآمادگی، شتاب، بیماری',
  },
  {
    id: 'swords-knight',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'شوالیهٔ شمشیرها',
    nameEn: 'Knight of Swords',
    uprightFa: 'مهارت، دلیری، کنشِ قاطع، دفاع، نیروی تند، اما گاه خشم و ستیز',
    reversedFa: 'بی‌احتیاطی، تندروی، بی‌پروایی، پرخاشِ پراکنده، ویرانی',
  },
  {
    id: 'swords-queen',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'ملکهٔ شمشیرها',
    nameEn: 'Queen of Swords',
    uprightFa: 'زنِ تیزبین، مستقل و صادق، اما گاه بیوگی، اندوه، جدایی',
    reversedFa: 'بدخواهی، تعصب، نیرنگ، سردی، تلخی، سنگ‌دلی',
  },
  {
    id: 'swords-king',
    arcana: 'minor',
    suit: 'swords',
    nameFa: 'شاهِ شمشیرها',
    nameEn: 'King of Swords',
    uprightFa: 'داوری، اقتدار، فرمان، خردِ تیز، قانون، وضوحِ ذهن، حقیقت',
    reversedFa: 'سنگ‌دلی، کژی، بدعهدی، نیّتِ بد، سوءاستفاده از قدرت',
  },
  {
    id: 'pentacles-01',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'آسِ سکه‌ها',
    nameEn: 'Ace of Pentacles',
    uprightFa: 'خرسندیِ کامل، سعادت، رونق، زر، ثروتِ نو، فرصتِ مادی',
    reversedFa: 'رویِ تاریکِ ثروت، آز، فرصتی از دست رفته',
  },
  {
    id: 'pentacles-02',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'دوی سکه‌ها',
    nameEn: 'Two of Pentacles',
    uprightFa: 'توازن، دست‌به‌دست‌کردن، سرخوشی، اما گاه مانع و آشوب، سازگاری',
    reversedFa: 'سرخوشیِ ساختگی، ازهم‌گسیختگی، نامه و پیام',
  },
  {
    id: 'pentacles-03',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'سهٔ سکه‌ها',
    nameEn: 'Three of Pentacles',
    uprightFa: 'کارِ ماهرانه، پیشه، هم‌کاری، چیرگی، نام و آوازه',
    reversedFa: 'میان‌مایگی، سست‌کاری، هم‌کاریِ ضعیف، کارِ بی‌کیفیت',
  },
  {
    id: 'pentacles-04',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'چهارِ سکه‌ها',
    nameEn: 'Four of Pentacles',
    uprightFa: 'نگه‌داشتِ دارایی، پس‌انداز، امنیت، هدیه، میراث',
    reversedFa: 'تعلیق، تأخیر، آز و انبارکردن، یا بخششِ سخاوتمندانه',
  },
  {
    id: 'pentacles-05',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'پنجِ سکه‌ها',
    nameEn: 'Five of Pentacles',
    uprightFa: 'تنگناهای مادی، تهی‌دستی، سختی، ناامنی، اما گاه هم‌دلیِ دلدادگان',
    reversedFa: 'بی‌سامانی، ویرانی، اما آغازِ بهبود از سختی',
  },
  {
    id: 'pentacles-06',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'ششِ سکه‌ها',
    nameEn: 'Six of Pentacles',
    uprightFa: 'بخشش، سخاوت، نیکوکاری، هم‌رساندنِ ثروت، رونقِ کنونی',
    reversedFa: 'آز، حسادت، توهم، بخششِ مشروط، بدهی',
  },
  {
    id: 'pentacles-07',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'هفتِ سکه‌ها',
    nameEn: 'Seven of Pentacles',
    uprightFa: 'صبر، پرورش، چشم‌به‌راهِ رشد، پول، داد‌وستد، سرمایه‌گذاری',
    reversedFa: 'دلواپسیِ مالی، بی‌صبری، سرمایه‌گذاریِ بد، تلاشِ هدررفته',
  },
  {
    id: 'pentacles-08',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'هشتِ سکه‌ها',
    nameEn: 'Eight of Pentacles',
    uprightFa: 'کار، پیشه‌آموزی، مهارت، پشتکار، توجه به جزئیات',
    reversedFa: 'بلندپروازیِ پوچ، خودنمایی، آز، مهارتِ به‌کژی‌رفته',
  },
  {
    id: 'pentacles-09',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'نهٔ سکه‌ها',
    nameEn: 'Nine of Pentacles',
    uprightFa: 'دوراندیشی، امنیت، کامیابی، فراوانی، اتکا به خود، آسایشِ ناب',
    reversedFa: 'نیرنگ، پروژهٔ بربادرفته، بدعهدی، وابستگیِ مالی',
  },
  {
    id: 'pentacles-10',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'دهٔ سکه‌ها',
    nameEn: 'Ten of Pentacles',
    uprightFa: 'ثروت، خانواده، میراث، خانهٔ استوار، رونقِ پایدار',
    reversedFa: 'بخت‌آزمایی، زیان، دزدی، نزاعِ خانوادگی، ویرانیِ مالی',
  },
  {
    id: 'pentacles-page',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'پیکِ سکه‌ها',
    nameEn: 'Page of Pentacles',
    uprightFa: 'آموختن، پژوهش، تأمل، خبر، بلندپروازی، آغازی تازه، پشتکار',
    reversedFa: 'ولخرجی، تن‌آسایی، خبرِ ناخوش، درنگ، پیش‌رفتِ اندک',
  },
  {
    id: 'pentacles-knight',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'شوالیهٔ سکه‌ها',
    nameEn: 'Knight of Pentacles',
    uprightFa: 'سودمندی، مسئولیت، درستی، کارِ سخت، اتکاپذیری، صبر',
    reversedFa: 'رخوت، تنبلی، رکود، دل‌سردی، بی‌دقتی، ملالِ روزمره',
  },
  {
    id: 'pentacles-queen',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'ملکهٔ سکه‌ها',
    nameEn: 'Queen of Pentacles',
    uprightFa: 'فراوانی، سخاوت، شکوه، امنیت، پرورش‌گر و عمل‌گرا',
    reversedFa: 'بدگمانی، ترس، بی‌اعتمادی، خودمحوری، غفلت، بی‌تعادلی',
  },
  {
    id: 'pentacles-king',
    arcana: 'minor',
    suit: 'pentacles',
    nameFa: 'شاهِ سکه‌ها',
    nameEn: 'King of Pentacles',
    uprightFa: 'دلیری، کارْدانی، خردِ عملی، ثروت، امنیت، پشتیبانی مطمئن',
    reversedFa: 'فساد، ضعف، آز، خطر، تصمیمِ مالیِ بد، مادی‌گری',
  },
];
