export type CardSuit = 'hearts' | 'diamonds' | 'clubs' | 'spades';

/** One card of the 52-card deck. Meanings are faithful Persian renderings
 *  of traditional cartomancy keyword meanings (read upright). */
export interface PlayingCard {
  id: string;
  suit: CardSuit;
  rank: string;
  nameFa: string;
  nameEn: string;
  meaningFa: string;
}

/** The full 52-card deck, by suit then rank. Held in code — small and
 *  static, so no database; the draw indexes straight into this array. */
export const CARDS_DECK: readonly PlayingCard[] = [
  {
    id: 'cards-hearts-A',
    suit: 'hearts',
    rank: 'A',
    nameFa: 'آسِ دل',
    nameEn: 'Ace of Hearts',
    meaningFa: 'خانه، عشق، عشقِ تازه، شادی، خبرِ خوش',
  },
  {
    id: 'cards-hearts-2',
    suit: 'hearts',
    rank: '2',
    nameFa: 'دوی دل',
    nameEn: 'Two of Hearts',
    meaningFa: 'شراکت، پیوند، عشقِ دوسویه، نامزدی، کامیابی در رابطه',
  },
  {
    id: 'cards-hearts-3',
    suit: 'hearts',
    rank: '3',
    nameFa: 'سهٔ دل',
    nameEn: 'Three of Hearts',
    meaningFa: 'احتیاط در عشق، دودلی، حرفی شتاب‌زده که پشیمانی می‌آورد',
  },
  {
    id: 'cards-hearts-4',
    suit: 'hearts',
    rank: '4',
    nameFa: 'چهارِ دل',
    nameEn: 'Four of Hearts',
    meaningFa: 'تغییر در رابطه، ازدواجِ به‌تعویق‌افتاده، خرسندیِ دیررس',
  },
  {
    id: 'cards-hearts-5',
    suit: 'hearts',
    rank: '5',
    nameFa: 'پنجِ دل',
    nameEn: 'Five of Hearts',
    meaningFa: 'حسادت، دگرگونیِ دل، رنجشی کوچک میانِ دوستان',
  },
  {
    id: 'cards-hearts-6',
    suit: 'hearts',
    rank: '6',
    nameFa: 'ششِ دل',
    nameEn: 'Six of Hearts',
    meaningFa: 'سخاوت، اعتماد، هدیه یا پیشنهادی نامنتظر',
  },
  {
    id: 'cards-hearts-7',
    suit: 'hearts',
    rank: '7',
    nameFa: 'هفتِ دل',
    nameEn: 'Seven of Hearts',
    meaningFa: 'قول‌های شکسته، دوستی دمدمی و نامطمئن',
  },
  {
    id: 'cards-hearts-8',
    suit: 'hearts',
    rank: '8',
    nameFa: 'هشتِ دل',
    nameEn: 'Eight of Hearts',
    meaningFa: 'دعوت، هدیه، مهمان، مهر، گردهماییِ شاد',
  },
  {
    id: 'cards-hearts-9',
    suit: 'hearts',
    rank: '9',
    nameFa: 'نهٔ دل',
    nameEn: 'Nine of Hearts',
    meaningFa: 'کارتِ آرزو، خرسندی، برآورده‌شدنِ آرزوها',
  },
  {
    id: 'cards-hearts-10',
    suit: 'hearts',
    rank: '10',
    nameFa: 'دهٔ دل',
    nameEn: 'Ten of Hearts',
    meaningFa: 'بختِ خوش، شادی، کامیابی که بر کارت‌های بدِ کنارش می‌چربد',
  },
  {
    id: 'cards-hearts-J',
    suit: 'hearts',
    rank: 'J',
    nameFa: 'سربازِ دل',
    nameEn: 'Jack of Hearts',
    meaningFa: 'دوست یا دلداده‌ای عزیز، جوانی گرم‌دل',
  },
  {
    id: 'cards-hearts-Q',
    suit: 'hearts',
    rank: 'Q',
    nameFa: 'بی‌بیِ دل',
    nameEn: 'Queen of Hearts',
    meaningFa: 'زنی مهربان، وفادار و منصف، لطیف و دلسوز',
  },
  {
    id: 'cards-hearts-K',
    suit: 'hearts',
    rank: 'K',
    nameFa: 'شاهِ دل',
    nameEn: 'King of Hearts',
    meaningFa: 'مردی مهربان، سخاوتمند و خوش‌قلب، مشاوری گرم',
  },
  {
    id: 'cards-diamonds-A',
    suit: 'diamonds',
    rank: 'A',
    nameFa: 'آسِ خشت',
    nameEn: 'Ace of Diamonds',
    meaningFa: 'پیام یا نامه‌ای مهم، یک حلقه، رسیدنِ پول',
  },
  {
    id: 'cards-diamonds-2',
    suit: 'diamonds',
    rank: '2',
    nameFa: 'دوی خشت',
    nameEn: 'Two of Diamonds',
    meaningFa: 'عشق یا پیوندِ کاریِ جدی، شراکتی با مخالفت',
  },
  {
    id: 'cards-diamonds-3',
    suit: 'diamonds',
    rank: '3',
    nameFa: 'سهٔ خشت',
    nameEn: 'Three of Diamonds',
    meaningFa: 'نزاع، اوراقِ حقوقی، اختلافِ خانگی یا مالی',
  },
  {
    id: 'cards-diamonds-4',
    suit: 'diamonds',
    rank: '4',
    nameFa: 'چهارِ خشت',
    nameEn: 'Four of Diamonds',
    meaningFa: 'ارث یا دردسرِ مالی، رازی فاش‌شده',
  },
  {
    id: 'cards-diamonds-5',
    suit: 'diamonds',
    rank: '5',
    nameFa: 'پنجِ خشت',
    nameEn: 'Five of Diamonds',
    meaningFa: 'کامیابی در کار، رونق، خبرِ خوشِ خانوادگی',
  },
  {
    id: 'cards-diamonds-6',
    suit: 'diamonds',
    rank: '6',
    nameFa: 'ششِ خشت',
    nameEn: 'Six of Diamonds',
    meaningFa: 'تکرارِ مشکلاتِ رابطه، ازدواجِ دوم',
  },
  {
    id: 'cards-diamonds-7',
    suit: 'diamonds',
    rank: '7',
    nameFa: 'هفتِ خشت',
    nameEn: 'Seven of Diamonds',
    meaningFa: 'زیانی کوچک، انتقاد، پس‌رفتِ کاری، شایعه',
  },
  {
    id: 'cards-diamonds-8',
    suit: 'diamonds',
    rank: '8',
    nameFa: 'هشتِ خشت',
    nameEn: 'Eight of Diamonds',
    meaningFa: 'سفر، ازدواج در سالِ بالا، پول از راهِ سفر',
  },
  {
    id: 'cards-diamonds-9',
    suit: 'diamonds',
    rank: '9',
    nameFa: 'نهٔ خشت',
    nameEn: 'Nine of Diamonds',
    meaningFa: 'شگفتی، کارهای نو، بی‌قراری، خبرِ مالیِ نامنتظر',
  },
  {
    id: 'cards-diamonds-10',
    suit: 'diamonds',
    rank: '10',
    nameFa: 'دهٔ خشت',
    nameEn: 'Ten of Diamonds',
    meaningFa: 'ثروت، رونق، سفر، تغییری خوش در امورِ مالی',
  },
  {
    id: 'cards-diamonds-J',
    suit: 'diamonds',
    rank: 'J',
    nameFa: 'سربازِ خشت',
    nameEn: 'Jack of Diamonds',
    meaningFa: 'پیام‌آورِ خبر، جوانی خودخواه و نامطمئن',
  },
  {
    id: 'cards-diamonds-Q',
    suit: 'diamonds',
    rank: 'Q',
    nameFa: 'بی‌بیِ خشت',
    nameEn: 'Queen of Diamonds',
    meaningFa: 'زنی عشوه‌گر و زیرک، گاه فضول',
  },
  {
    id: 'cards-diamonds-K',
    suit: 'diamonds',
    rank: 'K',
    nameFa: 'شاهِ خشت',
    nameEn: 'King of Diamonds',
    meaningFa: 'مردی مقتدر و کاسب و سرسخت، اگر با او دربیفتی خطرناک',
  },
  {
    id: 'cards-clubs-A',
    suit: 'clubs',
    rank: 'A',
    nameFa: 'آسِ گشنیز',
    nameEn: 'Ace of Clubs',
    meaningFa: 'ثروت، رونق، خبرِ خوش، آوازه، کامیابی',
  },
  {
    id: 'cards-clubs-2',
    suit: 'clubs',
    rank: '2',
    nameFa: 'دوی گشنیز',
    nameEn: 'Two of Clubs',
    meaningFa: 'مخالفت، دلسردی، مانع و تأخیر در نقشه‌ها',
  },
  {
    id: 'cards-clubs-3',
    suit: 'clubs',
    rank: '3',
    nameFa: 'سهٔ گشنیز',
    nameEn: 'Three of Clubs',
    meaningFa: 'ازدواج، شاید بیش از یک‌بار، کامیابی با تلاش',
  },
  {
    id: 'cards-clubs-4',
    suit: 'clubs',
    rank: '4',
    nameFa: 'چهارِ گشنیز',
    nameEn: 'Four of Clubs',
    meaningFa: 'هشدار در برابرِ بی‌ثباتی، تغییر، خطرِ زیان',
  },
  {
    id: 'cards-clubs-5',
    suit: 'clubs',
    rank: '5',
    nameFa: 'پنجِ گشنیز',
    nameEn: 'Five of Clubs',
    meaningFa: 'دوستی نو، یاری و پشتیبانی، ازدواجی خوب',
  },
  {
    id: 'cards-clubs-6',
    suit: 'clubs',
    rank: '6',
    nameFa: 'ششِ گشنیز',
    nameEn: 'Six of Clubs',
    meaningFa: 'کامیابی در کار، کمکِ مالیِ دیگران، رونقِ پایدار',
  },
  {
    id: 'cards-clubs-7',
    suit: 'clubs',
    rank: '7',
    nameFa: 'هفتِ گشنیز',
    nameEn: 'Seven of Clubs',
    meaningFa: 'بختِ خوش، اما مراقبِ دردسر از جنسِ مخالف باش',
  },
  {
    id: 'cards-clubs-8',
    suit: 'clubs',
    rank: '8',
    nameFa: 'هشتِ گشنیز',
    nameEn: 'Eight of Clubs',
    meaningFa: 'دردسر از آز، عطشِ پول، مخالفت',
  },
  {
    id: 'cards-clubs-9',
    suit: 'clubs',
    rank: '9',
    nameFa: 'نهٔ گشنیز',
    nameEn: 'Nine of Clubs',
    meaningFa: 'دستاورد، بخت، کامروایی، اما نخست اختلاف با دوستان',
  },
  {
    id: 'cards-clubs-10',
    suit: 'clubs',
    rank: '10',
    nameFa: 'دهٔ گشنیز',
    nameEn: 'Ten of Clubs',
    meaningFa: 'پولِ نامنتظر، بختِ خوش، سفر از آب، کامیابی',
  },
  {
    id: 'cards-clubs-J',
    suit: 'clubs',
    rank: 'J',
    nameFa: 'سربازِ گشنیز',
    nameEn: 'Jack of Clubs',
    meaningFa: 'دوستی مطمئن و سخاوتمند، دلداده‌ای صادق',
  },
  {
    id: 'cards-clubs-Q',
    suit: 'clubs',
    rank: 'Q',
    nameFa: 'بی‌بیِ گشنیز',
    nameEn: 'Queen of Clubs',
    meaningFa: 'زنی مطمئن، گرم و یاری‌گر، دوستی خوب',
  },
  {
    id: 'cards-clubs-K',
    suit: 'clubs',
    rank: 'K',
    nameFa: 'شاهِ گشنیز',
    nameEn: 'King of Clubs',
    meaningFa: 'مردی صادق، سخاوتمند و مهربان، مشاوری وفادار',
  },
  {
    id: 'cards-spades-A',
    suit: 'spades',
    rank: 'A',
    nameFa: 'آسِ پیک',
    nameEn: 'Ace of Spades',
    meaningFa: 'بدبیاری، پایان، نقطهٔ چرخشِ بزرگ، خبرِ بد',
  },
  {
    id: 'cards-spades-2',
    suit: 'spades',
    rank: '2',
    nameFa: 'دوی پیک',
    nameEn: 'Two of Spades',
    meaningFa: 'جدایی، فریب، انتخابی سخت، جابه‌جایی',
  },
  {
    id: 'cards-spades-3',
    suit: 'spades',
    rank: '3',
    nameFa: 'سهٔ پیک',
    nameEn: 'Three of Spades',
    meaningFa: 'بی‌وفایی، شکافِ رابطه، اشک، جدایی‌ها',
  },
  {
    id: 'cards-spades-4',
    suit: 'spades',
    rank: '4',
    nameFa: 'چهارِ پیک',
    nameEn: 'Four of Spades',
    meaningFa: 'بیماری، حسادت، دردسرِ کاری، نیاز به استراحت',
  },
  {
    id: 'cards-spades-5',
    suit: 'spades',
    rank: '5',
    nameFa: 'پنجِ پیک',
    nameEn: 'Five of Spades',
    meaningFa: 'دلواپسی و پس‌رفت، اما کامیابی پس از تلاش',
  },
  {
    id: 'cards-spades-6',
    suit: 'spades',
    rank: '6',
    nameFa: 'ششِ پیک',
    nameEn: 'Six of Spades',
    meaningFa: 'بهبودِ تدریجی، سفر، سودی کوچک پس از سختی',
  },
  {
    id: 'cards-spades-7',
    suit: 'spades',
    rank: '7',
    nameFa: 'هفتِ پیک',
    nameEn: 'Seven of Spades',
    meaningFa: 'زیان، اندوه، هشدار، پندی نادیده‌گرفته',
  },
  {
    id: 'cards-spades-8',
    suit: 'spades',
    rank: '8',
    nameFa: 'هشتِ پیک',
    nameEn: 'Eight of Spades',
    meaningFa: 'دلسردی، مخالفت، هشدار به رهاکردنِ نقشه‌ها',
  },
  {
    id: 'cards-spades-9',
    suit: 'spades',
    rank: '9',
    nameFa: 'نهٔ پیک',
    nameEn: 'Nine of Spades',
    meaningFa: 'بدترین کارت، بدشانسی، زیان، بیماری، غم',
  },
  {
    id: 'cards-spades-10',
    suit: 'spades',
    rank: '10',
    nameFa: 'دهٔ پیک',
    nameEn: 'Ten of Spades',
    meaningFa: 'نگرانی، بدبیاری، اندوه، خنثی‌کنندهٔ کارت‌های خوبِ کنار',
  },
  {
    id: 'cards-spades-J',
    suit: 'spades',
    rank: 'J',
    nameFa: 'سربازِ پیک',
    nameEn: 'Jack of Spades',
    meaningFa: 'جوانی خوش‌نیت اما نامطمئن، یک رقیب',
  },
  {
    id: 'cards-spades-Q',
    suit: 'spades',
    rank: 'Q',
    nameFa: 'بی‌بیِ پیک',
    nameEn: 'Queen of Spades',
    meaningFa: 'بیوه‌زن، زنی خیانت‌کار یا بدخواه، شایعه‌ساز',
  },
  {
    id: 'cards-spades-K',
    suit: 'spades',
    rank: 'K',
    nameFa: 'شاهِ پیک',
    nameEn: 'King of Spades',
    meaningFa: 'مردی جاه‌طلب و قاضی‌مسلک و مقتدر، اگر با او دربیفتی بی‌رحم',
  },
];
